// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDiguZyNR_k1nojaigCli3rzZFQcnH5O8',
    appId: '1:892939612008:web:c7858a3d2313d2915830dd',
    messagingSenderId: '892939612008',
    projectId: 'smartinventory-fc333',
    authDomain: 'smartinventory-fc333.firebaseapp.com',
    storageBucket: 'smartinventory-fc333.firebasestorage.app',
    measurementId: 'G-GT49QWHT84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdCMHWNV2UvXzyJf7cHWFATMcWXsZnLmk',
    appId: '1:892939612008:android:707ef5c4bafa10635830dd',
    messagingSenderId: '892939612008',
    projectId: 'smartinventory-fc333',
    storageBucket: 'smartinventory-fc333.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3MLxEjNo8_Km2aFr4Bt-EcCqNQ0t8TIM',
    appId: '1:892939612008:ios:2f8e316f961471b85830dd',
    messagingSenderId: '892939612008',
    projectId: 'smartinventory-fc333',
    storageBucket: 'smartinventory-fc333.firebasestorage.app',
    iosBundleId: 'com.example.smartinventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3MLxEjNo8_Km2aFr4Bt-EcCqNQ0t8TIM',
    appId: '1:892939612008:ios:2f8e316f961471b85830dd',
    messagingSenderId: '892939612008',
    projectId: 'smartinventory-fc333',
    storageBucket: 'smartinventory-fc333.firebasestorage.app',
    iosBundleId: 'com.example.smartinventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDiguZyNR_k1nojaigCli3rzZFQcnH5O8',
    appId: '1:892939612008:web:2923cd4ee187f8425830dd',
    messagingSenderId: '892939612008',
    projectId: 'smartinventory-fc333',
    authDomain: 'smartinventory-fc333.firebaseapp.com',
    storageBucket: 'smartinventory-fc333.firebasestorage.app',
    measurementId: 'G-LZG4L58TMT',
  );
}
